# Generated by Django 4.1.2 on 2023-01-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_category',
            field=models.CharField(choices=[('mens', 'mens'), ('womans', 'womans'), ('kids', 'kids')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
