# Generated by Django 4.1.2 on 2023-01-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productdetails_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='product_stock',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
